[program:door]
command=/usr/local/bin/gunicorn wsgi --bind localhost:2000 --workers 2 --worker-class gevent
directory=/var/www/door
autostart=true
autorestart=true

redirect_stderr=true

stdout_logfile=/var/log/supervisor/door_stdout.log
stderr_logfile=/var/log/supervisor/door_stderr.log